version: 1.0.{build}
image: Visual Studio 2019 Preview
skip_tags: true

before_build:
- cd src
- dotnet restore
- cd ..
- choco install opencover.portable
- choco install codecov
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

build_script:
    - dotnet build src -c Release
  
test_script:
- cd src
- dotnet test
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:test -filter:"+[DiscordBot.Core*]* -[DiscordBot.Core.xUnit.Tests*]*" -output:".\coverage.xml" -oldstyle
- codecov -f "coverage.xml